class brunetteC:

        Questions = [["Brunette: Are you from around here?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette: Have you ever fallen asleep on a date?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette: Have you ever fought a Dragon?\nA) Yes\nB) Maybe\nC) No "],
                ["Brunette Set 2: Did you ever want to join the knighthood\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 2: Do you like to ride horses?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 2: Do you want to go for a walk?\nA) Yes\nB) Maybe\nC) No "],
                ["Brunette Set 3: Do you like jousting?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 3: Do you like my jewelry?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 3: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Brunette  Set 4: Do you know the blacksmith?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 4: Do you like my hair?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 4: Are you good at cooking?\nA) Yes\nB) Maybe\nC) No "],
                ["Brunette Set 5: Do you go to the beach often?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 5: Is your sword custom made?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 5: Have you ever climbed a mountain?\nA) Yes\nB) Maybe\nC) No "],
                ["Brunette Set 6: Are you loyal to our king?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 6: Have you ever bought another woman flowers? \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 6: So you like the sunset?\nA) Yes\nB) Maybe\nC) No "],                
                ["Brunette Set 7: Have you ever walked down a creek; barefoot?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 7: Do you enjoy the theater?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 7: Do you play any instruments?\nA) Yes\nB) Maybe\nC) No "],
                ["Brunette Set 8: Are you scared of goblins?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 8: Do you think the earth is flat?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 8: Have you ever traveled before?\nA) Yes\nB) Maybe\nC) No "],
                ["Brunette Set 9: Do you usually sleep in on the fortnight\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 9: Have you paid the kings tax? \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 9: Do you have any pets? \nA) Yes\nB) Maybe\nC) No "]]
