class brunetteC:

        Questions = [["Brunette: Are you from around here?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Brunette Set 2: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 2: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 2: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Brunette Set 3: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 3: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 3: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Brunette  Set 4: Do you know the blacksmith?\nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 4: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 4: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Brunette Set 5: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 5: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 5: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Brunette Set 6: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 6: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 6: Q3 \nA) Yes\nB) Maybe\nC) No "],                
                ["Brunette Set 7: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 7: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 7: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Brunette Set 8: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 8: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 8: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Brunette Set 9: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 9: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Brunette Set 9: Q3 \nA) Yes\nB) Maybe\nC) No "]]