class redheadC:

    Questions = [["Red-Head: Can you buy me glass of mead?\nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Red-Head Set 2: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 2: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 2: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Red-Head Set 3: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 3: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 3: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Red-Head  Set 4: Are your parents or noble blood?\nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 4: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 4: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Red-Head Set 5: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 5: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 5: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Red-Head Set 6: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 6: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 6: Q3 \nA) Yes\nB) Maybe\nC) No "],                
                ["Red-Head Set 7: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 7: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 7: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Red-Head Set 8: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 8: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 8: Q3 \nA) Yes\nB) Maybe\nC) No "],
                ["Red-Head Set 9: Q1 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 9: Q2 \nA) Yes\nB) Maybe\nC) No ",
                    "Red-Head Set 9: Q3 \nA) Yes\nB) Maybe\nC) No "]]
